name: mav_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0-290.3.beta <4.0.0'

# Add regular dependencies here.
dependencies: 
  dio: ^5.1.1
  json_annotation: ^4.8.0
  uuid: ^3.0.7
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.1
  json_serializable: ^6.6.1
  lints: ^2.0.0
